# Generated by Django 4.2.7 on 2026-07-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_portfolioproject_experience_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hero_description',
            field=models.TextField(blank=True, help_text='Short tagline shown on the hero section'),
        ),
    ]
