# Generated by Django 4.2.7 on 2026-07-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_hero_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_images/'),
        ),
    ]
