# Generated by Django 4.2.7 on 2026-07-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_education',
            field=models.BooleanField(default=True, help_text='Show education section in portfolio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_experience',
            field=models.BooleanField(default=True, help_text='Show work experience section in portfolio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_projects',
            field=models.BooleanField(default=True, help_text='Show portfolio projects section in portfolio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_services',
            field=models.BooleanField(default=True, help_text='Show services section in portfolio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_skills',
            field=models.BooleanField(default=True, help_text='Show skills section in portfolio'),
        ),
    ]
