# Generated by Django 4.2.7 on 2026-07-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_show_education_profile_show_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Show this education in portfolio'),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Show this experience in portfolio'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Show this project in portfolio'),
        ),
    ]
