# Generated by Django 4.2.7 on 2026-07-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_education_is_visible_experience_is_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='List of additional image paths'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='video_links',
            field=models.JSONField(blank=True, default=list, help_text='List of video URLs (YouTube, Vimeo, etc.)'),
        ),
    ]
