# Generated by Django 4.2.7 on 2026-07-02 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_portfolioproject_images_portfolioproject_video_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioproject',
            name='images',
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='users.portfolioproject')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
