# Generated by Django 4.2.7 on 2026-07-02 01:46

from django.db import migrations, models
import users.storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_portfolioproject_images_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=users.storage.SupabaseStorage(), upload_to='portfolio_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_image',
            field=models.ImageField(blank=True, null=True, storage=users.storage.SupabaseStorage(), upload_to='about_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=users.storage.SupabaseStorage(), upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(storage=users.storage.SupabaseStorage(), upload_to='portfolio_images/'),
        ),
    ]
