# Generated by Django 4.2.7 on 2026-07-02 17:24

from django.db import migrations, models
import users.storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_portfolioproject_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=users.storage.SupabaseStorage(), upload_to='portfolio_images/'),
        ),
    ]
