# Generated by Django 4.2.7 on 2026-07-02 19:17

from django.db import migrations, models
import django.db.models.deletion
import users.storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_projectimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_testimonials',
            field=models.BooleanField(default=True, help_text='Show testimonials section in portfolio'),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=users.storage.SupabaseStorage(), upload_to='testimonials/')),
                ('name', models.CharField(blank=True, help_text='Name of the person giving testimonial', max_length=200)),
                ('role', models.CharField(blank=True, help_text='Role/Title of the person', max_length=200)),
                ('is_visible', models.BooleanField(default=True, help_text='Show this testimonial in portfolio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='users.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
