# Generated by Django 4.2.7 on 2026-07-02 19:27

from django.db import migrations, models
import users.storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_show_testimonials_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=users.storage.SupabaseStorage(), upload_to='testimonials/'),
        ),
    ]
