# Generated by Django 4.2.7 on 2026-07-02 19:43

from django.db import migrations, models
import django.db.models.deletion
import users.storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_testimonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_certificates',
            field=models.BooleanField(default=True, help_text='Show certificates section in portfolio'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, storage=users.storage.SupabaseStorage(), upload_to='certificates/')),
                ('title', models.CharField(blank=True, help_text='Certificate title', max_length=200)),
                ('issuer', models.CharField(blank=True, help_text='Issuing organization', max_length=200)),
                ('date', models.DateField(blank=True, help_text='Date issued', null=True)),
                ('is_visible', models.BooleanField(default=True, help_text='Show this certificate in portfolio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='users.profile')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
