# Generated by Django 4.2.7 on 2026-07-09 17:11

from django.db import migrations, models


def convert_email_to_list(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        # Use raw SQL to convert email strings to JSON arrays
        with schema_editor.connection.cursor() as cursor:
            # Update non-null email values to JSON array format
            cursor.execute("""
                UPDATE users_profile 
                SET email = CASE 
                    WHEN email IS NULL OR email = '' THEN '[]'::json
                    WHEN email::text ~ '^\[.*\]$' THEN email::json
                    ELSE json_build_array(email)
                END
            """)
    else:
        # For other databases, use ORM
        Profile = apps.get_model('users', 'Profile')
        for profile in Profile.objects.all():
            if profile.email:
                if isinstance(profile.email, str):
                    profile.email = [profile.email]
                elif not isinstance(profile.email, list):
                    profile.email = []
            else:
                profile.email = []
            profile.save(update_fields=['email'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_show_certificates_certificate'),
    ]

    operations = [
        migrations.RunPython(convert_email_to_list, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.JSONField(blank=True, default=list, help_text='List of email addresses'),
        ),
    ]
