-- Create users table for Django custom User model
-- This matches the Django User model in users/models.py

CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    password VARCHAR(128) NOT NULL,
    last_login TIMESTAMP WITH TIME ZONE,
    is_superuser BOOLEAN NOT NULL DEFAULT FALSE,
    username VARCHAR(150) NOT NULL UNIQUE,
    first_name VARCHAR(150) NOT NULL DEFAULT '',
    last_name VARCHAR(150) NOT NULL DEFAULT '',
    is_staff BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    date_joined TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    email VARCHAR(254) NOT NULL,
    user_type VARCHAR(20) NOT NULL DEFAULT 'EDITOR',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Create index on username for faster lookups
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);

-- Create index on email for faster lookups
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- Create index on user_type for filtering
CREATE INDEX IF NOT EXISTS idx_users_user_type ON users(user_type);

-- Enable Row Level Security (optional - comment out if not needed)
-- ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow authenticated users to read users (optional)
-- CREATE POLICY "Allow authenticated read access" ON users
--     FOR SELECT
--     TO authenticated
--     USING (true);

-- Create a policy to allow service role to manage users (optional)
-- CREATE POLICY "Allow service role full access" ON users
--     FOR ALL
--     TO service_role
--     USING (true)
--     WITH CHECK (true);
